[
  {
    "Target": "Cargo.lock",
    "Type": "cargo",
    "Vulnerabilities": [
      {
        "VulnerabilityID": "RUSTSEC-2019-0001",
        "PkgName": "ammonia",
        "InstalledVersion": "1.9.0",
        "FixedVersion": "\u003e= 2.1.0",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://rustsec.org/advisories/RUSTSEC-2019-0001",
        "Title": "Uncontrolled recursion leads to abort in HTML serialization",
        "Description": "Affected versions of this crate did use recursion for serialization of HTML\nDOM trees.\n\nThis allows an attacker to cause abort due to stack overflow by providing\na pathologically nested input.\n\nThe flaw was corrected by serializing the DOM tree iteratively instead.",
        "Severity": "UNKNOWN",
        "References": [
          "https://github.com/rust-ammonia/ammonia/blob/master/CHANGELOG.md#210"
        ]
      },
      {
        "VulnerabilityID": "RUSTSEC-2016-0001",
        "PkgName": "openssl",
        "InstalledVersion": "0.8.3",
        "FixedVersion": "\u003e= 0.9.0",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://rustsec.org/advisories/RUSTSEC-2016-0001",
        "Title": "SSL/TLS MitM vulnerability due to insecure defaults",
        "Description": "All versions of rust-openssl prior to 0.9.0 contained numerous insecure defaults\nincluding off-by-default certificate verification and no API to perform hostname\nverification.\n\nUnless configured correctly by a developer, these defaults could allow an attacker\nto perform man-in-the-middle attacks.\n\nThe problem was addressed in newer versions by enabling certificate verification\nby default and exposing APIs to perform hostname verification. Use the\n`SslConnector` and `SslAcceptor` types to take advantage of these new features\n(as opposed to the lower-level `SslContext` type).",
        "Severity": "UNKNOWN",
        "References": [
          "https://github.com/sfackler/rust-openssl/releases/tag/v0.9.0"
        ]
      },
      {
        "VulnerabilityID": "RUSTSEC-2019-0035",
        "PkgName": "rand_core",
        "InstalledVersion": "0.4.0",
        "FixedVersion": "^ 0.3.1, \u003e= 0.4.2",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://rustsec.org/advisories/RUSTSEC-2019-0035",
        "Title": "Unaligned memory access",
        "Description": "Affected versions of this crate violated alignment when casting byte slices to\ninteger slices, resulting in undefined behavior.\n\nThe flaw was corrected by Ralf Jung and Diggory Hardy.",
        "Severity": "UNKNOWN",
        "References": [
          "https://github.com/rust-random/rand/blob/master/rand_core/CHANGELOG.md#050---2019-06-06"
        ]
      },
      {
        "VulnerabilityID": "RUSTSEC-2018-0018",
        "PkgName": "smallvec",
        "InstalledVersion": "0.6.9",
        "FixedVersion": "\u003e= 0.6.13",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://rustsec.org/advisories/RUSTSEC-2018-0018",
        "Title": "smallvec creates uninitialized value of any type",
        "Description": "Affected versions of this crate called `mem::uninitialized()` to create values of a user-supplied type `T`.\nThis is unsound e.g. if `T` is a reference type (which must be non-null and thus may not remain uninitialized).\n \nThe flaw was corrected by avoiding the use of `mem::uninitialized()`, using `MaybeUninit` instead.",
        "Severity": "UNKNOWN",
        "References": [
          "https://github.com/servo/rust-smallvec/issues/126"
        ]
      },
      {
        "VulnerabilityID": "RUSTSEC-2019-0009",
        "PkgName": "smallvec",
        "InstalledVersion": "0.6.9",
        "FixedVersion": "\u003e= 0.6.10",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://rustsec.org/advisories/RUSTSEC-2019-0009",
        "Title": "Double-free and use-after-free in SmallVec::grow()",
        "Description": "Attempting to call `grow` on a spilled SmallVec with a value equal to the current capacity causes it to free the existing data. This performs a double free immediately and may lead to use-after-free on subsequent accesses to the SmallVec contents.\n\nAn attacker that controls the value passed to `grow` may exploit this flaw to obtain memory contents or gain remote code execution.\n\nCredits to @ehuss for discovering, reporting and fixing the bug.",
        "Severity": "UNKNOWN",
        "References": [
          "https://github.com/servo/rust-smallvec/issues/148"
        ]
      },
      {
        "VulnerabilityID": "RUSTSEC-2019-0012",
        "PkgName": "smallvec",
        "InstalledVersion": "0.6.9",
        "FixedVersion": "\u003e= 0.6.10",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://rustsec.org/advisories/RUSTSEC-2019-0012",
        "Title": "Memory corruption in SmallVec::grow()",
        "Description": "Attempting to call `grow` on a spilled SmallVec with a value less than the current capacity causes corruption of memory allocator data structures.\n\nAn attacker that controls the value passed to `grow` may exploit this flaw to obtain memory contents or gain remote code execution.\n\nCredits to @ehuss for discovering, reporting and fixing the bug.",
        "Severity": "UNKNOWN",
        "References": [
          "https://github.com/servo/rust-smallvec/issues/149"
        ]
      },
      {
        "VulnerabilityID": "RUSTSEC-2021-0003",
        "PkgName": "smallvec",
        "InstalledVersion": "0.6.9",
        "FixedVersion": "\u003e= 0.6.14, \u003c 1.0.0, \u003e= 1.6.1",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://rustsec.org/advisories/RUSTSEC-2021-0003",
        "Title": "Buffer overflow in SmallVec::insert_many",
        "Description": "A bug in the `SmallVec::insert_many` method caused it to allocate a buffer that was smaller than needed.  It then wrote past the end of the buffer, causing a buffer overflow and memory corruption on the heap.\n\nThis bug was only triggered if the iterator passed to `insert_many` yielded more items than the lower bound returned from its `size_hint` method.\n \nThe flaw was corrected in smallvec 0.6.14 and 1.6.1, by ensuring that additional space is always reserved for each item inserted.  The fix also simplified the implementation of `insert_many` to use less unsafe code, so it is easier to verify its correctness.\n\nThank you to Yechan Bae (@Qwaz) and the Rust group at Georgia Techâ€™s SSLab for finding and reporting this bug.",
        "Severity": "UNKNOWN",
        "References": [
          "https://github.com/servo/rust-smallvec/issues/252"
        ]
      },
      {
        "VulnerabilityID": "RUSTSEC-2018-0017",
        "PkgName": "tempdir",
        "InstalledVersion": "0.3.7",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://rustsec.org/advisories/RUSTSEC-2018-0017",
        "Title": "`tempdir` crate has been deprecated; use `tempfile` instead",
        "Description": "The [`tempdir`](https://crates.io/crates/tempdir) crate has been deprecated\nand the functionality is merged into [`tempfile`](https://crates.io/crates/tempfile).",
        "Severity": "UNKNOWN",
        "References": [
          "https://github.com/rust-lang-deprecated/tempdir/pull/46"
        ]
      }
    ]
  },
  {
    "Target": "Pipfile.lock",
    "Type": "pipenv",
    "Vulnerabilities": [
      {
        "VulnerabilityID": "CVE-2019-19844",
        "PkgName": "django",
        "InstalledVersion": "2.0.9",
        "FixedVersion": "3.0.1, 2.2.9, 1.11.27",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-19844",
        "Title": "Django: crafted email address allows account takeover",
        "Description": "Django before 1.11.27, 2.x before 2.2.9, and 3.x before 3.0.1 allows account takeover. A suitably crafted email address (that is equal to an existing user's email address after case transformation of Unicode characters) would allow an attacker to be sent a password reset token for the matched user account. (One mitigation in the new releases is to send password reset tokens only to the registered user email address.)",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-640"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 5,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 9.8
          }
        },
        "References": [
          "http://packetstormsecurity.com/files/155872/Django-Account-Hijack.html",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-19844",
          "https://docs.djangoproject.com/en/dev/releases/security/",
          "https://github.com/advisories/GHSA-vfq6-hq5r-27r6",
          "https://groups.google.com/forum/#!topic/django-announce/3oaB2rVH3a0",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HCM2DPUI7TOZWN4A6JFQFUVQ2XGE7GUD/",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-19844",
          "https://seclists.org/bugtraq/2020/Jan/9",
          "https://security.gentoo.org/glsa/202004-17",
          "https://security.netapp.com/advisory/ntap-20200110-0003/",
          "https://ubuntu.com/security/notices/USN-4224-1",
          "https://usn.ubuntu.com/4224-1/",
          "https://www.debian.org/security/2020/dsa-4598",
          "https://www.djangoproject.com/weblog/2019/dec/18/security-releases/"
        ],
        "PublishedDate": "2019-12-18T19:15:00Z",
        "LastModifiedDate": "2020-01-08T04:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-7471",
        "PkgName": "django",
        "InstalledVersion": "2.0.9",
        "FixedVersion": "3.0.3, 2.2.10, 1.11.28",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-7471",
        "Title": "django: potential SQL injection via StringAgg(delimiter)",
        "Description": "Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-89"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 7.5,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 9.8
          }
        },
        "References": [
          "http://www.openwall.com/lists/oss-security/2020/02/03/1",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7471",
          "https://docs.djangoproject.com/en/3.0/releases/security/",
          "https://github.com/advisories/GHSA-hmr4-m2h5-33qx",
          "https://github.com/django/django/commit/eb31d845323618d688ad429479c6dda973056136",
          "https://groups.google.com/forum/#!topic/django-announce/X45S86X5bZI",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-7471",
          "https://seclists.org/bugtraq/2020/Feb/30",
          "https://security.gentoo.org/glsa/202004-17",
          "https://security.netapp.com/advisory/ntap-20200221-0006/",
          "https://ubuntu.com/security/notices/USN-4264-1",
          "https://usn.ubuntu.com/4264-1/",
          "https://www.debian.org/security/2020/dsa-4629",
          "https://www.djangoproject.com/weblog/2020/feb/03/security-releases/",
          "https://www.openwall.com/lists/oss-security/2020/02/03/1"
        ],
        "PublishedDate": "2020-02-03T12:15:00Z",
        "LastModifiedDate": "2020-06-19T03:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2019-6975",
        "PkgName": "django",
        "InstalledVersion": "2.0.9",
        "FixedVersion": "2.1.6, 2.0.11, 1.11.19",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-6975",
        "Title": "python-django: memory exhaustion in django.utils.numberformat.format()",
        "Description": "Django 1.11.x before 1.11.19, 2.0.x before 2.0.11, and 2.1.x before 2.1.6 allows Uncontrolled Memory Consumption via a malicious attacker-supplied value to the django.utils.numberformat.format() function.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-770"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V3Score": 5.3
          }
        },
        "References": [
          "http://www.securityfocus.com/bid/106964",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6975",
          "https://docs.djangoproject.com/en/dev/releases/security/",
          "https://github.com/advisories/GHSA-wh4h-v3f2-r2pp",
          "https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-6975",
          "https://seclists.org/bugtraq/2019/Jul/10",
          "https://ubuntu.com/security/notices/USN-3890-1",
          "https://usn.ubuntu.com/3890-1/",
          "https://www.debian.org/security/2019/dsa-4476",
          "https://www.djangoproject.com/weblog/2019/feb/11/security-releases/",
          "https://www.openwall.com/lists/oss-security/2019/02/11/1"
        ],
        "PublishedDate": "2019-02-11T13:29:00Z",
        "LastModifiedDate": "2020-08-24T17:37:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-9402",
        "PkgName": "django",
        "InstalledVersion": "2.0.9",
        "FixedVersion": "3.0.4, 2.2.11, 1.11.29",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-9402",
        "Title": "django: potential SQL injection via \"tolerance\" parameter in GIS functions and aggregates on Oracle",
        "Description": "Django 1.11 before 1.11.29, 2.2 before 2.2.11, and 3.0 before 3.0.4 allows SQL Injection if untrusted data is used as a tolerance parameter in GIS functions and aggregates on Oracle. By passing a suitably crafted tolerance to GIS functions and aggregates on Oracle, it was possible to break escaping and inject malicious SQL.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-89"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:S/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 6.5,
            "V3Score": 8.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 8.8
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-9402",
          "https://docs.djangoproject.com/en/3.0/releases/security/",
          "https://github.com/advisories/GHSA-3gh2-xw74-jmcw",
          "https://groups.google.com/forum/#!topic/django-announce/fLUh_pOaKrY",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-9402",
          "https://security.gentoo.org/glsa/202004-17",
          "https://security.netapp.com/advisory/ntap-20200327-0004/",
          "https://ubuntu.com/security/notices/USN-4296-1",
          "https://usn.ubuntu.com/4296-1/",
          "https://www.debian.org/security/2020/dsa-4705",
          "https://www.djangoproject.com/weblog/2020/mar/04/security-releases/"
        ],
        "PublishedDate": "2020-03-05T15:15:00Z",
        "LastModifiedDate": "2020-07-14T17:28:00Z"
      },
      {
        "VulnerabilityID": "CVE-2019-3498",
        "PkgName": "django",
        "InstalledVersion": "2.0.9",
        "FixedVersion": "2.1.5, 2.0.10, 1.11.18",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-3498",
        "Title": "python-django: Content spoofing via URL path in default 404 page",
        "Description": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
            "V2Score": 4.3,
            "V3Score": 6.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N",
            "V3Score": 4.3
          }
        },
        "References": [
          "http://www.securityfocus.com/bid/106453",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-3498",
          "https://docs.djangoproject.com/en/dev/releases/security/",
          "https://github.com/advisories/GHSA-337x-4q8g-prc5",
          "https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ",
          "https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-3498",
          "https://ubuntu.com/security/notices/USN-3851-1",
          "https://usn.ubuntu.com/3851-1/",
          "https://www.debian.org/security/2019/dsa-4363",
          "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"
        ],
        "PublishedDate": "2019-01-09T23:29:00Z",
        "LastModifiedDate": "2019-04-23T13:11:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-13254",
        "PkgName": "django",
        "InstalledVersion": "2.0.9",
        "FixedVersion": "3.0.7, 2.2.13",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-13254",
        "Title": "django: potential data leakage via malformed memcached keys",
        "Description": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-295"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:P/I:N/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
            "V2Score": 4.3,
            "V3Score": 5.9
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 5.9
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-13254",
          "https://docs.djangoproject.com/en/3.0/releases/security/",
          "https://github.com/advisories/GHSA-wpjr-j57x-wxfw",
          "https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
          "https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-13254",
          "https://security.netapp.com/advisory/ntap-20200611-0002/",
          "https://ubuntu.com/security/notices/USN-4381-1",
          "https://ubuntu.com/security/notices/USN-4381-2",
          "https://usn.ubuntu.com/4381-1/",
          "https://usn.ubuntu.com/4381-2/",
          "https://www.debian.org/security/2020/dsa-4705",
          "https://www.djangoproject.com/weblog/2020/jun/03/security-releases",
          "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
          "https://www.oracle.com/security-alerts/cpujan2021.html"
        ],
        "PublishedDate": "2020-06-03T14:15:00Z",
        "LastModifiedDate": "2021-01-20T15:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-13596",
        "PkgName": "django",
        "InstalledVersion": "2.0.9",
        "FixedVersion": "3.0.7, 2.2.13",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-13596",
        "Title": "django: possible XSS via admin ForeignKeyRawIdWidget",
        "Description": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-79"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
            "V2Score": 4.3,
            "V3Score": 6.1
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-13596",
          "https://docs.djangoproject.com/en/3.0/releases/security/",
          "https://github.com/advisories/GHSA-2m34-jcjv-45xf",
          "https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-13596",
          "https://security.netapp.com/advisory/ntap-20200611-0002/",
          "https://ubuntu.com/security/notices/USN-4381-1",
          "https://ubuntu.com/security/notices/USN-4381-2",
          "https://usn.ubuntu.com/4381-1/",
          "https://usn.ubuntu.com/4381-2/",
          "https://www.debian.org/security/2020/dsa-4705",
          "https://www.djangoproject.com/weblog/2020/jun/03/security-releases",
          "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
          "https://www.oracle.com/security-alerts/cpujan2021.html"
        ],
        "PublishedDate": "2020-06-03T14:15:00Z",
        "LastModifiedDate": "2021-01-20T15:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-33203",
        "PkgName": "django",
        "InstalledVersion": "2.0.9",
        "FixedVersion": "3.2.4, 3.1.12, 2.2.24",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33203",
        "Title": "django: Potential directory traversal via ``admindocs``",
        "Description": "Django before 2.2.24, 3.x before 3.1.12, and 3.2.x before 3.2.4 has a potential directory traversal via django.contrib.admindocs. Staff members could use the TemplateDetailView view to check the existence of arbitrary files. Additionally, if (and only if) the default admindocs templates have been customized by application developers to also show file contents, then not only the existence but also the file contents would have been exposed. In other words, there is directory traversal outside of the template root directories.",
        "Severity": "MEDIUM",
        "CVSS": {
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 4.4
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33203",
          "https://docs.djangoproject.com/en/3.2/releases/security/",
          "https://github.com/advisories/GHSA-68w8-qjq3-2gfm",
          "https://groups.google.com/forum/#!forum/django-announce",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-33203",
          "https://ubuntu.com/security/notices/USN-4975-1",
          "https://ubuntu.com/security/notices/USN-4975-2",
          "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/"
        ],
        "PublishedDate": "2021-06-08T18:15:00Z",
        "LastModifiedDate": "2021-06-08T18:58:00Z"
      },
      {
        "VulnerabilityID": "pyup.io-37132",
        "PkgName": "django-cors-headers",
        "InstalledVersion": "2.5.2",
        "FixedVersion": "3.0.0",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "Title": "In django-cors-headers version 3.0.0, ``CORS_ORIGIN_WHITELIST`` requires URI schemes, and optionally ports. This is part of the CORS specification (Section 3.2 \u003chttps://tools.ietf.org/html/rfc6454section-3.2\u003e) that was not implemented in this library, except from with the ``CORS_ORIGIN_REGEX_WHITELIST`` setting. It fixes a security issue where the CORS middleware would allow requests between schemes, for example from insecure ``http://`` Origins to a secure ``https://`` site.\r\n\r\nYou will need to update your whitelist to include schemes, for example from this:\r\n\r\nCORS_ORIGIN_WHITELIST = ['example.com']\r\n\r\nto this:\r\n\r\nCORS_ORIGIN_WHITELIST = ['https://example.com']",
        "Severity": "UNKNOWN"
      },
      {
        "VulnerabilityID": "CVE-2020-25626",
        "PkgName": "djangorestframework",
        "InstalledVersion": "3.9.2",
        "FixedVersion": "3.11.2",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-25626",
        "Title": "django-rest-framework: XSS Vulnerability in API viewer",
        "Description": "A flaw was found in Django REST Framework versions before 3.12.0 and before 3.11.2. When using the browseable API viewer, Django REST Framework fails to properly escape certain strings that can come from user input. This allows a user who can control those strings to inject malicious \u003cscript\u003e tags, leading to a cross-site-scripting (XSS) vulnerability.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-79"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
            "V2Score": 4.3,
            "V3Score": 6.1
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
            "V3Score": 5.4
          }
        },
        "References": [
          "https://bugzilla.redhat.com/show_bug.cgi?id=1878635",
          "https://github.com/advisories/GHSA-fx83-3ph3-9j2q",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-25626",
          "https://security.netapp.com/advisory/ntap-20201016-0003/"
        ],
        "PublishedDate": "2020-09-30T20:15:00Z",
        "LastModifiedDate": "2020-10-16T11:15:00Z"
      },
      {
        "VulnerabilityID": "pyup.io-40104",
        "PkgName": "gunicorn",
        "InstalledVersion": "19.9.0",
        "FixedVersion": "19.10.0, 20.0.1",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "Title": "Gunicorn 20.0.1 fixes chunked encoding support to prevent any request smuggling for security purposes.",
        "Severity": "UNKNOWN"
      },
      {
        "VulnerabilityID": "pyup.io-40105",
        "PkgName": "gunicorn",
        "InstalledVersion": "19.9.0",
        "FixedVersion": "19.10.0",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "Title": "Gunicorn 19.10.0 includes a security fix to prevent HTTP desync attack.",
        "Severity": "UNKNOWN"
      },
      {
        "VulnerabilityID": "CVE-2021-21240",
        "PkgName": "httplib2",
        "InstalledVersion": "0.12.1",
        "FixedVersion": "0.19.0",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-21240",
        "Title": "python-httplib2: Regular expression denial of service via malicious header",
        "Description": "httplib2 is a comprehensive HTTP client library for Python. In httplib2 before version 0.19.0, a malicious server which responds with long series of \"\\xa0\" characters in the \"www-authenticate\" header may cause Denial of Service (CPU burn while parsing header) of the httplib2 client accessing said server. This is fixed in version 0.19.0 which contains a new implementation of auth headers parsing using the pyparsing library.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-400"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-21240",
          "https://github.com/advisories/GHSA-93xj-8mrv-444m",
          "https://github.com/httplib2/httplib2/commit/bd9ee252c8f099608019709e22c0d705e98d26bc",
          "https://github.com/httplib2/httplib2/pull/182",
          "https://github.com/httplib2/httplib2/security/advisories/GHSA-93xj-8mrv-444m",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-21240",
          "https://pypi.org/project/httplib2"
        ],
        "PublishedDate": "2021-02-08T20:15:00Z",
        "LastModifiedDate": "2021-02-12T14:56:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-11078",
        "PkgName": "httplib2",
        "InstalledVersion": "0.12.1",
        "FixedVersion": "0.18.0",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-11078",
        "Title": "python-httplib2: CRLF injection via an attacker controlled unescaped part of uri for httplib2.Http.request function",
        "Description": "In httplib2 before version 0.18.0, an attacker controlling unescaped part of uri for `httplib2.Http.request()` could change request headers and body, send additional hidden requests to same server. This vulnerability impacts software that uses httplib2 with uri constructed by string concatenation, as opposed to proper urllib building with escaping. This has been fixed in 0.18.0.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-93",
          "CWE-74"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:N",
            "V2Score": 4.3,
            "V3Score": 6.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:N",
            "V3Score": 6.8
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11078",
          "https://github.com/advisories/GHSA-gg84-qgv9-w4pq",
          "https://github.com/httplib2/httplib2/commit/a1457cc31f3206cf691d11d2bf34e98865873e9e",
          "https://github.com/httplib2/httplib2/security/advisories/GHSA-gg84-qgv9-w4pq",
          "https://linux.oracle.com/cve/CVE-2020-11078.html",
          "https://linux.oracle.com/errata/ELSA-2020-5947.html",
          "https://lists.apache.org/thread.html/r23711190c2e98152cb6f216b95090d5eeb978543bb7e0bad22ce47fc@%3Cissues.beam.apache.org%3E",
          "https://lists.apache.org/thread.html/r4d35dac106fab979f0db75a07fc4e320ad848b722103e79667ff99e1@%3Cissues.beam.apache.org%3E",
          "https://lists.apache.org/thread.html/r69a462e690b5f2c3d418a288a2c98ae764d58587bd0b5d6ab141f25f@%3Cissues.beam.apache.org%3E",
          "https://lists.apache.org/thread.html/r7f364000066748299b331b615ba51c62f55ab5b201ddce9a22d98202@%3Cissues.beam.apache.org%3E",
          "https://lists.apache.org/thread.html/rad8872fc99f670958c2774e2bf84ee32a3a0562a0c787465cf3dfa23@%3Cissues.beam.apache.org%3E",
          "https://lists.apache.org/thread.html/rc9eff9572946142b657c900fe63ea4bbd3535911e8d4ce4d08fe4b89@%3Ccommits.allura.apache.org%3E",
          "https://lists.debian.org/debian-lts-announce/2020/06/msg00000.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IXCX2AWROGWGY5GXR7VN3BKF34A2FO6J/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PZJ3D6JSM7CFZESZZKGUW2VX55BOSOXI/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-11078"
        ],
        "PublishedDate": "2020-05-20T16:15:00Z",
        "LastModifiedDate": "2020-08-19T18:56:00Z"
      },
      {
        "VulnerabilityID": "pyup.io-38303",
        "PkgName": "httplib2",
        "InstalledVersion": "0.12.1",
        "FixedVersion": "0.18.0",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "Title": "Httplib2 0.18.0 is an important security update to patch a CWE-93 CRLF injection vulnerability which forces %xx quote of space, CR, LF characters in uri. See: \u003chttps://cwe.mitre.org/data/definitions/93.html\u003e.",
        "Severity": "UNKNOWN"
      },
      {
        "VulnerabilityID": "CVE-2020-28493",
        "PkgName": "jinja2",
        "InstalledVersion": "2.10.1",
        "FixedVersion": "2.11.3",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-28493",
        "Title": "python-jinja2: ReDOS vulnerability due to the sub-pattern",
        "Description": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDoS vulnerability is mainly due to the `_punctuation_re regex` operator and its use of multiple wildcards. The last wildcard is the most exploitable as it searches for trailing punctuation. This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
        "Severity": "MEDIUM",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V2Score": 5,
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://github.com/advisories/GHSA-g3rq-g295-4j3m",
          "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20",
          "https://github.com/pallets/jinja/pull/1343",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PVAKCOO7VBVUBM3Q6CBBTPBFNP5NDXF4/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-28493",
          "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994"
        ],
        "PublishedDate": "2021-02-01T20:15:00Z",
        "LastModifiedDate": "2021-03-22T16:34:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-29651",
        "PkgName": "py",
        "InstalledVersion": "1.8.0",
        "FixedVersion": "1.10.0",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-29651",
        "Title": "python-py: ReDoS in the py.path.svnwc component via mailicious input to blame functionality",
        "Description": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.",
        "Severity": "HIGH",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
            "V3Score": 4.3
          }
        },
        "References": [
          "https://github.com/advisories/GHSA-hj5v-574p-mj7c",
          "https://github.com/pytest-dev/py/issues/256",
          "https://github.com/pytest-dev/py/pull/257",
          "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AYWNYEV3FGDHPIHX4DDUDMFZ6NLCQRC4/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CHDTINIBJZ67T3W74QTBIY5LPKAXEOGR/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-29651"
        ],
        "PublishedDate": "2020-12-09T07:15:00Z",
        "LastModifiedDate": "2021-01-05T03:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-20270",
        "PkgName": "pygments",
        "InstalledVersion": "2.3.1",
        "FixedVersion": "2.7.4",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-20270",
        "Title": "python-pygments: infinite loop in SML lexer may lead to DoS",
        "Description": "An infinite loop in SMLLexer in Pygments versions 1.5 to 2.7.3 may lead to denial of service when performing syntax highlighting of a Standard ML (SML) source file, as demonstrated by input that only contains the \"exception\" keyword.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-835"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://bugzilla.redhat.com/show_bug.cgi?id=1922136",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-20270",
          "https://github.com/advisories/GHSA-9w8r-397f-prfh",
          "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html",
          "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-20270",
          "https://ubuntu.com/security/notices/USN-4885-1",
          "https://www.debian.org/security/2021/dsa-4889"
        ],
        "PublishedDate": "2021-03-23T17:15:00Z",
        "LastModifiedDate": "2021-05-06T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-27291",
        "PkgName": "pygments",
        "InstalledVersion": "2.3.1",
        "FixedVersion": "2.7.4",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-27291",
        "Title": "python-pygments: ReDos via crafted malicious input",
        "Description": "In pygments 1.1+, fixed in 2.7.4, the lexers used to parse programming languages rely heavily on regular expressions. Some of the regular expressions have exponential or cubic worst-case complexity and are vulnerable to ReDoS. By crafting malicious input, an attacker can cause a denial of service.",
        "Severity": "HIGH",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-27291",
          "https://gist.github.com/b-c-ds/b1a2cc0c68a35c57188575eb496de5ce",
          "https://github.com/advisories/GHSA-pq64-v7f5-gqh8",
          "https://github.com/pygments/pygments/commit/2e7e8c4a7b318f4032493773732754e418279a14",
          "https://lists.debian.org/debian-lts-announce/2021/03/msg00024.html",
          "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html",
          "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GSJRFHALQ7E3UV4FFMFU2YQ6LUDHAI55/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WSLD67LFGXOX2K5YNESSWAS4AGZIJTUQ/",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-27291",
          "https://ubuntu.com/security/notices/USN-4897-1",
          "https://www.debian.org/security/2021/dsa-4878",
          "https://www.debian.org/security/2021/dsa-4889"
        ],
        "PublishedDate": "2021-03-17T13:15:00Z",
        "LastModifiedDate": "2021-05-06T23:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2019-20477",
        "PkgName": "pyyaml",
        "InstalledVersion": "5.1",
        "FixedVersion": "5.2",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-20477",
        "Title": "PyYAML: command execution through python/object/apply constructor in FullLoader",
        "Description": "PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all functions because of a class deserialization issue, e.g., Popen is a class in the subprocess module. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-502"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 7.5,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 9.8
          }
        },
        "References": [
          "https://github.com/advisories/GHSA-3pqx-4fqf-j49f",
          "https://github.com/yaml/pyyaml/blob/master/CHANGES",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/33VBUY73AA6CTTYL3LRWHNFDULV7PFPN/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/52N5XS73Z5S4ZN7I7R56ICCPCTKCUV4H/",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-20477",
          "https://www.exploit-db.com/download/47655"
        ],
        "PublishedDate": "2020-02-19T04:15:00Z",
        "LastModifiedDate": "2020-03-01T00:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-14343",
        "PkgName": "pyyaml",
        "InstalledVersion": "5.1",
        "FixedVersion": "5.4",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-14343",
        "Title": "PyYAML: incomplete fix for CVE-2020-1747",
        "Description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 10,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 9.8
          }
        },
        "References": [
          "https://bugzilla.redhat.com/show_bug.cgi?id=1860466",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14343",
          "https://github.com/advisories/GHSA-8q59-q68h-6hv4",
          "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-14343",
          "https://ubuntu.com/security/notices/USN-4940-1"
        ],
        "PublishedDate": "2021-02-09T21:15:00Z",
        "LastModifiedDate": "2021-02-16T16:22:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-1747",
        "PkgName": "pyyaml",
        "InstalledVersion": "5.1",
        "FixedVersion": "5.3.1",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-1747",
        "Title": "PyYAML: arbitrary command execution through python/object/new when FullLoader is used",
        "Description": "A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 10,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 9.8
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html",
          "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html",
          "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747",
          "https://github.com/advisories/GHSA-6757-jp84-gxfx",
          "https://github.com/yaml/pyyaml/pull/386",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-1747"
        ],
        "PublishedDate": "2020-03-24T15:15:00Z",
        "LastModifiedDate": "2021-03-26T02:44:00Z"
      },
      {
        "VulnerabilityID": "CVE-2019-11324",
        "PkgName": "urllib3",
        "InstalledVersion": "1.24.1",
        "FixedVersion": "1.24.2",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-11324",
        "Title": "python-urllib3: Certification mishandle when error should be thrown",
        "Description": "The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-295"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html",
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html",
          "http://www.openwall.com/lists/oss-security/2019/04/19/1",
          "https://access.redhat.com/errata/RHSA-2019:3335",
          "https://access.redhat.com/errata/RHSA-2019:3590",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11324",
          "https://github.com/advisories/GHSA-mh33-7rrq-662w",
          "https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4",
          "https://linux.oracle.com/cve/CVE-2019-11324.html",
          "https://linux.oracle.com/errata/ELSA-2020-2068.html",
          "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-11324",
          "https://ubuntu.com/security/notices/USN-3990-1",
          "https://usn.ubuntu.com/3990-1/",
          "https://www.openwall.com/lists/oss-security/2019/04/17/3"
        ],
        "PublishedDate": "2019-04-18T21:29:00Z",
        "LastModifiedDate": "2021-06-15T21:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-33503",
        "PkgName": "urllib3",
        "InstalledVersion": "1.24.1",
        "FixedVersion": "1.26.5",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33503",
        "Title": "python-urllib3: Catastrophic backtracking in URL authority parser",
        "Description": "A flaw was found in python-urllib3. When provided with a URL containing many @ characters in the authority component, the authority's regular expression exhibits catastrophic backtracking. This flaw causes a denial of service if a URL is passed as a parameter or redirected via an HTTP redirect. The highest threat from this vulnerability is to system availability.",
        "Severity": "HIGH",
        "CVSS": {
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503",
          "https://github.com/advisories/GHSA-q2q7-5pp4-w6pg",
          "https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec",
          "https://github.com/urllib3/urllib3/security/advisories/GHSA-q2q7-5pp4-w6pg",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-33503"
        ]
      },
      {
        "VulnerabilityID": "CVE-2019-11236",
        "PkgName": "urllib3",
        "InstalledVersion": "1.24.1",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-11236",
        "Title": "python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service",
        "Description": "In the urllib3 library through 1.24.1 for Python, CRLF injection is possible if the attacker controls the request parameter.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-93"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
            "V2Score": 4.3,
            "V3Score": 6.1
          },
          "redhat": {
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "V3Score": 6.5
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html",
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html",
          "https://access.redhat.com/errata/RHSA-2019:2272",
          "https://access.redhat.com/errata/RHSA-2019:3335",
          "https://access.redhat.com/errata/RHSA-2019:3590",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11236",
          "https://github.com/urllib3/urllib3/issues/1553",
          "https://linux.oracle.com/cve/CVE-2019-11236.html",
          "https://linux.oracle.com/errata/ELSA-2020-2081.html",
          "https://lists.debian.org/debian-lts-announce/2019/06/msg00016.html",
          "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/R62XGEYPUTXMRHGX5I37EBCGQ5COHGKR/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TBI45HO533KYHNB5YRO43TBYKA3E3VRL/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/",
          "https://ubuntu.com/security/notices/USN-3990-1",
          "https://ubuntu.com/security/notices/USN-3990-2",
          "https://usn.ubuntu.com/3990-1/",
          "https://usn.ubuntu.com/3990-2/"
        ],
        "PublishedDate": "2019-04-15T15:29:00Z",
        "LastModifiedDate": "2021-06-15T21:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-26137",
        "PkgName": "urllib3",
        "InstalledVersion": "1.24.1",
        "FixedVersion": "1.25.9",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-26137",
        "Title": "python-urllib3: CRLF injection via HTTP request method",
        "Description": "urllib3 before 1.25.9 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of putrequest(). NOTE: this is similar to CVE-2020-26116.",
        "Severity": "MEDIUM",
        "CweIDs": [
          "CWE-74"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "V2Score": 6.4,
            "V3Score": 6.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "V3Score": 6.5
          }
        },
        "References": [
          "https://bugs.python.org/issue39603",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-26137",
          "https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b",
          "https://github.com/urllib3/urllib3/pull/1800",
          "https://linux.oracle.com/cve/CVE-2020-26137.html",
          "https://linux.oracle.com/errata/ELSA-2021-1631.html",
          "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html",
          "https://ubuntu.com/security/notices/USN-4570-1",
          "https://usn.ubuntu.com/4570-1/"
        ],
        "PublishedDate": "2020-09-30T18:15:00Z",
        "LastModifiedDate": "2021-06-15T21:15:00Z"
      }
    ]
  },
  {
    "Target": "yarn.lock",
    "Type": "yarn",
    "Vulnerabilities": [
      {
        "VulnerabilityID": "CVE-2021-23364",
        "PkgName": "browserslist",
        "InstalledVersion": "4.14.2",
        "FixedVersion": "4.16.5",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-23364",
        "Title": "browserslist: parsing of invalid queries could result in Regular Expression Denial of Service (ReDoS)",
        "Description": "The package browserslist from 4.0.0 and before 4.16.5 are vulnerable to Regular Expression Denial of Service (ReDoS) during parsing of queries.",
        "Severity": "MEDIUM",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V2Score": 5,
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://github.com/advisories/GHSA-w8qv-6jwh-64r5",
          "https://github.com/browserslist/browserslist/blob/e82f32d1d4100d6bc79ea0b6b6a2d281a561e33c/index.js%23L472-L474",
          "https://github.com/browserslist/browserslist/commit/c091916910dfe0b5fd61caad96083c6709b02d98",
          "https://github.com/browserslist/browserslist/pull/593",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-23364",
          "https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1277182",
          "https://snyk.io/vuln/SNYK-JS-BROWSERSLIST-1090194"
        ],
        "PublishedDate": "2021-04-28T16:15:00Z",
        "LastModifiedDate": "2021-05-05T20:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-28469",
        "PkgName": "glob-parent",
        "InstalledVersion": "3.1.0",
        "FixedVersion": "5.1.2",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-28469",
        "Title": "nodejs-glob-parent: Regular expression denial of service",
        "Description": "This affects the package glob-parent before 5.1.2. The enclosure regex used to check for strings ending in enclosure containing path separator.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-400"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28469",
          "https://github.com/advisories/GHSA-ww39-953v-wcq6",
          "https://github.com/gulpjs/glob-parent/blob/6ce8d11f2f1ed8e80a9526b1dc8cf3aa71f43474/index.js%23L9",
          "https://github.com/gulpjs/glob-parent/commit/f9231168b0041fea3f8f954b3cceb56269fc6366",
          "https://github.com/gulpjs/glob-parent/pull/36",
          "https://github.com/gulpjs/glob-parent/releases/tag/v5.1.2",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-28469",
          "https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSBOWERGITHUBES128-1059093",
          "https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1059092",
          "https://snyk.io/vuln/SNYK-JS-GLOBPARENT-1016905"
        ],
        "PublishedDate": "2021-06-03T16:15:00Z",
        "LastModifiedDate": "2021-06-11T18:37:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-33502",
        "PkgName": "normalize-url",
        "InstalledVersion": "1.9.1",
        "FixedVersion": "6.0.1, 5.3.1, 4.5.1",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33502",
        "Title": "normalize-url: ReDoS for data URLs",
        "Description": "The normalize-url package before 4.5.1, 5.x before 5.3.1, and 6.x before 6.0.1 for Node.js has a ReDoS (regular expression denial of service) issue because it has exponential performance for data: URLs.",
        "Severity": "HIGH",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://github.com/advisories/GHSA-px4h-xg32-q955",
          "https://github.com/sindresorhus/normalize-url/releases/tag/v6.0.1",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-33502",
          "https://snyk.io/vuln/SNYK-JS-NORMALIZEURL-1296539"
        ],
        "PublishedDate": "2021-05-24T16:15:00Z",
        "LastModifiedDate": "2021-06-11T14:05:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-33502",
        "PkgName": "normalize-url",
        "InstalledVersion": "3.3.0",
        "FixedVersion": "6.0.1, 5.3.1, 4.5.1",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33502",
        "Title": "normalize-url: ReDoS for data URLs",
        "Description": "The normalize-url package before 4.5.1, 5.x before 5.3.1, and 6.x before 6.0.1 for Node.js has a ReDoS (regular expression denial of service) issue because it has exponential performance for data: URLs.",
        "Severity": "HIGH",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://github.com/advisories/GHSA-px4h-xg32-q955",
          "https://github.com/sindresorhus/normalize-url/releases/tag/v6.0.1",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-33502",
          "https://snyk.io/vuln/SNYK-JS-NORMALIZEURL-1296539"
        ],
        "PublishedDate": "2021-05-24T16:15:00Z",
        "LastModifiedDate": "2021-06-11T14:05:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-23368",
        "PkgName": "postcss",
        "InstalledVersion": "7.0.21",
        "FixedVersion": "8.2.10, 7.0.36",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-23368",
        "Title": "nodejs-postcss: Regular expression denial of service during source map parsing",
        "Description": "The package postcss from 7.0.0 and before 8.2.10 are vulnerable to Regular Expression Denial of Service (ReDoS) during source map parsing.",
        "Severity": "MEDIUM",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V2Score": 5,
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23368",
          "https://github.com/advisories/GHSA-hwj9-h5mp-3pm3",
          "https://github.com/postcss/postcss/commit/8682b1e4e328432ba692bed52326e84439cec9e4",
          "https://github.com/postcss/postcss/commit/b6f3e4d5a8d7504d553267f80384373af3a3dec5",
          "https://lists.apache.org/thread.html/r00158f5d770d75d0655c5eef1bdbc6150531606c8f8bcb778f0627be@%3Cdev.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/r16e295b4f02d81b79981237d602cb0b9e59709bafaa73ac98be7cef1@%3Cdev.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/r49afb49b38748897211b1f89c3a64dc27f9049474322b05715695aab@%3Cdev.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/r5acd89f3827ad9a9cad6d24ed93e377f7114867cd98cfba616c6e013@%3Ccommits.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/r8def971a66cf3e375178fbee752e1b04a812a047cc478ad292007e33@%3Cdev.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/rad5af2044afb51668b1008b389ac815a28ecea9eb75ae2cab5a00ebb@%3Ccommits.myfaces.apache.org%3E",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-23368",
          "https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1244795",
          "https://snyk.io/vuln/SNYK-JS-POSTCSS-1090595"
        ],
        "PublishedDate": "2021-04-12T14:15:00Z",
        "LastModifiedDate": "2021-06-11T14:08:00Z"
      },
      {
        "VulnerabilityID": "CVE-2021-23368",
        "PkgName": "postcss",
        "InstalledVersion": "7.0.35",
        "FixedVersion": "8.2.10, 7.0.36",
        "Layer": {
          "DiffID": "sha256:8e1cc37b28281beaffeedb78aefc848497d2c086c098035cddc1ab74ad089cf2"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-23368",
        "Title": "nodejs-postcss: Regular expression denial of service during source map parsing",
        "Description": "The package postcss from 7.0.0 and before 8.2.10 are vulnerable to Regular Expression Denial of Service (ReDoS) during source map parsing.",
        "Severity": "MEDIUM",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V2Score": 5,
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V3Score": 5.3
          }
        },
        "References": [
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23368",
          "https://github.com/advisories/GHSA-hwj9-h5mp-3pm3",
          "https://github.com/postcss/postcss/commit/8682b1e4e328432ba692bed52326e84439cec9e4",
          "https://github.com/postcss/postcss/commit/b6f3e4d5a8d7504d553267f80384373af3a3dec5",
          "https://lists.apache.org/thread.html/r00158f5d770d75d0655c5eef1bdbc6150531606c8f8bcb778f0627be@%3Cdev.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/r16e295b4f02d81b79981237d602cb0b9e59709bafaa73ac98be7cef1@%3Cdev.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/r49afb49b38748897211b1f89c3a64dc27f9049474322b05715695aab@%3Cdev.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/r5acd89f3827ad9a9cad6d24ed93e377f7114867cd98cfba616c6e013@%3Ccommits.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/r8def971a66cf3e375178fbee752e1b04a812a047cc478ad292007e33@%3Cdev.myfaces.apache.org%3E",
          "https://lists.apache.org/thread.html/rad5af2044afb51668b1008b389ac815a28ecea9eb75ae2cab5a00ebb@%3Ccommits.myfaces.apache.org%3E",
          "https://nvd.nist.gov/vuln/detail/CVE-2021-23368",
          "https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1244795",
          "https://snyk.io/vuln/SNYK-JS-POSTCSS-1090595"
        ],
        "PublishedDate": "2021-04-12T14:15:00Z",
        "LastModifiedDate": "2021-06-11T14:08:00Z"
      }
    ]
  }
]